// Database types for CEO OS
// These will be regenerated with `supabase gen types` once the schema is applied

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          timezone: string;
          preferences: Json;
          onboarding_completed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          timezone?: string;
          preferences?: Json;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          timezone?: string;
          preferences?: Json;
          onboarding_completed?: boolean;
          updated_at?: string;
        };
      };
      daily_check_ins: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          energy_physical: number | null;
          energy_mental: number | null;
          energy_emotional: number | null;
          energy_word: string;
          meaningful_win: string;
          friction_point: string;
          let_go: string;
          tomorrow_priority: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          energy_physical?: number | null;
          energy_mental?: number | null;
          energy_emotional?: number | null;
          energy_word?: string;
          meaningful_win?: string;
          friction_point?: string;
          let_go?: string;
          tomorrow_priority?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          date?: string;
          energy_physical?: number | null;
          energy_mental?: number | null;
          energy_emotional?: number | null;
          energy_word?: string;
          meaningful_win?: string;
          friction_point?: string;
          let_go?: string;
          tomorrow_priority?: string;
          notes?: string | null;
          updated_at?: string;
        };
      };
      weekly_reviews: {
        Row: {
          id: string;
          user_id: string;
          week: string;
          start_date: string;
          end_date: string;
          moved_needle: string[];
          was_noise: string[];
          time_leaked: string;
          average_energy: number | null;
          best_day: string;
          best_day_why: string;
          worst_day: string;
          worst_day_why: string;
          who_energized: string;
          who_drained: string;
          should_connect: string;
          strategic_insight: string;
          adjustment: string;
          next_priorities: string[];
          gratitude: string;
          wins: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          week: string;
          start_date: string;
          end_date: string;
          moved_needle?: string[];
          was_noise?: string[];
          time_leaked?: string;
          average_energy?: number | null;
          best_day?: string;
          best_day_why?: string;
          worst_day?: string;
          worst_day_why?: string;
          who_energized?: string;
          who_drained?: string;
          should_connect?: string;
          strategic_insight?: string;
          adjustment?: string;
          next_priorities?: string[];
          gratitude?: string;
          wins?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          week?: string;
          start_date?: string;
          end_date?: string;
          moved_needle?: string[];
          was_noise?: string[];
          time_leaked?: string;
          average_energy?: number | null;
          best_day?: string;
          best_day_why?: string;
          worst_day?: string;
          worst_day_why?: string;
          who_energized?: string;
          who_drained?: string;
          should_connect?: string;
          strategic_insight?: string;
          adjustment?: string;
          next_priorities?: string[];
          gratitude?: string;
          wins?: string[];
          updated_at?: string;
        };
      };
      quarterly_reviews: {
        Row: {
          id: string;
          user_id: string;
          quarter: string;
          start_date: string;
          end_date: string;
          goal_progress: Json;
          life_map_scores: Json;
          average_energy: number | null;
          best_month: string;
          best_month_why: string;
          worst_month: string;
          worst_month_why: string;
          energizers: string[];
          drainers: string[];
          sustainable_pace: string;
          working_on_what_matters: string;
          time_gap: string;
          said_yes_shouldnt_have: string;
          missed_opportunity: string;
          key_wins: string[];
          unexpected_win: string;
          key_challenges: string[];
          persistent_problem: string;
          avoiding_decision: string;
          lesson_learned: string;
          new_knowledge: string;
          clearer_pattern: string;
          start_doing: string[];
          stop_doing: string[];
          continue_doing: string[];
          next_quarter_theme: string;
          next_priorities: string[];
          what_will_be_true: string;
          one_thing_easier: string;
          direction_still_accurate: string;
          needs_to_change: string;
          memory_insights: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          quarter: string;
          start_date: string;
          end_date: string;
          goal_progress?: Json;
          life_map_scores?: Json;
          average_energy?: number | null;
          best_month?: string;
          best_month_why?: string;
          worst_month?: string;
          worst_month_why?: string;
          energizers?: string[];
          drainers?: string[];
          sustainable_pace?: string;
          working_on_what_matters?: string;
          time_gap?: string;
          said_yes_shouldnt_have?: string;
          missed_opportunity?: string;
          key_wins?: string[];
          unexpected_win?: string;
          key_challenges?: string[];
          persistent_problem?: string;
          avoiding_decision?: string;
          lesson_learned?: string;
          new_knowledge?: string;
          clearer_pattern?: string;
          start_doing?: string[];
          stop_doing?: string[];
          continue_doing?: string[];
          next_quarter_theme?: string;
          next_priorities?: string[];
          what_will_be_true?: string;
          one_thing_easier?: string;
          direction_still_accurate?: string;
          needs_to_change?: string;
          memory_insights?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          quarter?: string;
          start_date?: string;
          end_date?: string;
          goal_progress?: Json;
          life_map_scores?: Json;
          average_energy?: number | null;
          best_month?: string;
          best_month_why?: string;
          worst_month?: string;
          worst_month_why?: string;
          energizers?: string[];
          drainers?: string[];
          sustainable_pace?: string;
          working_on_what_matters?: string;
          time_gap?: string;
          said_yes_shouldnt_have?: string;
          missed_opportunity?: string;
          key_wins?: string[];
          unexpected_win?: string;
          key_challenges?: string[];
          persistent_problem?: string;
          avoiding_decision?: string;
          lesson_learned?: string;
          new_knowledge?: string;
          clearer_pattern?: string;
          start_doing?: string[];
          stop_doing?: string[];
          continue_doing?: string[];
          next_quarter_theme?: string;
          next_priorities?: string[];
          what_will_be_true?: string;
          one_thing_easier?: string;
          direction_still_accurate?: string;
          needs_to_change?: string;
          memory_insights?: string[];
          updated_at?: string;
        };
      };
      annual_reviews: {
        Row: {
          id: string;
          user_id: string;
          year: number;
          start_date: string;
          end_date: string;
          one_sentence_summary: string;
          year_theme: string;
          goals_achieved: Json;
          life_map_scores: Json;
          top_wins: string[];
          proudest_moment: string;
          biggest_surprise: string;
          biggest_challenges: string[];
          what_didnt_work: string;
          what_would_do_differently: string;
          skills_gained: string[];
          lessons_learned: string[];
          most_important_lesson: string;
          key_relationships: string;
          relationship_changes: string;
          average_energy: number | null;
          health_summary: string;
          next_year_intention: string;
          next_year_word: string;
          gratitude: string;
          quotes_to_remember: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          year: number;
          start_date: string;
          end_date: string;
          one_sentence_summary?: string;
          year_theme?: string;
          goals_achieved?: Json;
          life_map_scores?: Json;
          top_wins?: string[];
          proudest_moment?: string;
          biggest_surprise?: string;
          biggest_challenges?: string[];
          what_didnt_work?: string;
          what_would_do_differently?: string;
          skills_gained?: string[];
          lessons_learned?: string[];
          most_important_lesson?: string;
          key_relationships?: string;
          relationship_changes?: string;
          average_energy?: number | null;
          health_summary?: string;
          next_year_intention?: string;
          next_year_word?: string;
          gratitude?: string;
          quotes_to_remember?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          year?: number;
          start_date?: string;
          end_date?: string;
          one_sentence_summary?: string;
          year_theme?: string;
          goals_achieved?: Json;
          life_map_scores?: Json;
          top_wins?: string[];
          proudest_moment?: string;
          biggest_surprise?: string;
          biggest_challenges?: string[];
          what_didnt_work?: string;
          what_would_do_differently?: string;
          skills_gained?: string[];
          lessons_learned?: string[];
          most_important_lesson?: string;
          key_relationships?: string;
          relationship_changes?: string;
          average_energy?: number | null;
          health_summary?: string;
          next_year_intention?: string;
          next_year_word?: string;
          gratitude?: string;
          quotes_to_remember?: Json;
          updated_at?: string;
        };
      };
      goals: {
        Row: {
          id: string;
          user_id: string;
          goal_type: string;
          period_start: number;
          period_end: number | null;
          theme: string;
          if_goes_well: string | null;
          critical_three: string[];
          anti_goals: string[];
          habits_to_build: Json;
          habits_to_break: Json;
          snapshot: string | null;
          where_live: string | null;
          what_do: string | null;
          key_people: string | null;
          typical_week: string | null;
          whats_different: string | null;
          big_bets: string[];
          needs_to_end: string[];
          needs_to_begin: string[];
          career: Json;
          relationships: Json;
          health: Json;
          finances: Json;
          meaning: Json;
          fun: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          goal_type: string;
          period_start: number;
          period_end?: number | null;
          theme?: string;
          if_goes_well?: string | null;
          critical_three?: string[];
          anti_goals?: string[];
          habits_to_build?: Json;
          habits_to_break?: Json;
          snapshot?: string | null;
          where_live?: string | null;
          what_do?: string | null;
          key_people?: string | null;
          typical_week?: string | null;
          whats_different?: string | null;
          big_bets?: string[];
          needs_to_end?: string[];
          needs_to_begin?: string[];
          career?: Json;
          relationships?: Json;
          health?: Json;
          finances?: Json;
          meaning?: Json;
          fun?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          goal_type?: string;
          period_start?: number;
          period_end?: number | null;
          theme?: string;
          if_goes_well?: string | null;
          critical_three?: string[];
          anti_goals?: string[];
          habits_to_build?: Json;
          habits_to_break?: Json;
          snapshot?: string | null;
          where_live?: string | null;
          what_do?: string | null;
          key_people?: string | null;
          typical_week?: string | null;
          whats_different?: string | null;
          big_bets?: string[];
          needs_to_end?: string[];
          needs_to_begin?: string[];
          career?: Json;
          relationships?: Json;
          health?: Json;
          finances?: Json;
          meaning?: Json;
          fun?: Json;
          updated_at?: string;
        };
      };
      north_star: {
        Row: {
          id: string;
          user_id: string;
          one_sentence: string;
          stage_of_life: string;
          primary_role: string;
          company: string;
          years_in_chapter: number;
          what_defines_chapter: string;
          area_rankings: Json;
          non_negotiables: string[];
          saying_no_to: string[];
          central_question: string;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          one_sentence?: string;
          stage_of_life?: string;
          primary_role?: string;
          company?: string;
          years_in_chapter?: number;
          what_defines_chapter?: string;
          area_rankings?: Json;
          non_negotiables?: string[];
          saying_no_to?: string[];
          central_question?: string;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          one_sentence?: string;
          stage_of_life?: string;
          primary_role?: string;
          company?: string;
          years_in_chapter?: number;
          what_defines_chapter?: string;
          area_rankings?: Json;
          non_negotiables?: string[];
          saying_no_to?: string[];
          central_question?: string;
          notes?: string;
          updated_at?: string;
        };
      };
      life_map: {
        Row: {
          id: string;
          user_id: string;
          snapshot_date: string;
          career_score: number | null;
          career_trend: string | null;
          career_note: string;
          relationships_score: number | null;
          relationships_trend: string | null;
          relationships_note: string;
          health_score: number | null;
          health_trend: string | null;
          health_note: string;
          finances_score: number | null;
          finances_trend: string | null;
          finances_note: string;
          meaning_score: number | null;
          meaning_trend: string | null;
          meaning_note: string;
          fun_score: number | null;
          fun_trend: string | null;
          fun_note: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          snapshot_date?: string;
          career_score?: number | null;
          career_trend?: string | null;
          career_note?: string;
          relationships_score?: number | null;
          relationships_trend?: string | null;
          relationships_note?: string;
          health_score?: number | null;
          health_trend?: string | null;
          health_note?: string;
          finances_score?: number | null;
          finances_trend?: string | null;
          finances_note?: string;
          meaning_score?: number | null;
          meaning_trend?: string | null;
          meaning_note?: string;
          fun_score?: number | null;
          fun_trend?: string | null;
          fun_note?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          snapshot_date?: string;
          career_score?: number | null;
          career_trend?: string | null;
          career_note?: string;
          relationships_score?: number | null;
          relationships_trend?: string | null;
          relationships_note?: string;
          health_score?: number | null;
          health_trend?: string | null;
          health_note?: string;
          finances_score?: number | null;
          finances_trend?: string | null;
          finances_note?: string;
          meaning_score?: number | null;
          meaning_trend?: string | null;
          meaning_note?: string;
          fun_score?: number | null;
          fun_trend?: string | null;
          fun_note?: string;
          updated_at?: string;
        };
      };
      memory: {
        Row: {
          id: string;
          user_id: string;
          executive_summary: string;
          strengths: string[];
          growth_edges: string[];
          energized_by: string[];
          drained_by: string[];
          optimal_conditions: string;
          over_indexes: string;
          under_weights: string;
          blind_spots: string[];
          goal_archaeology: Json;
          insights_by_year: Json;
          lessons_work: string[];
          lessons_relationships: string[];
          lessons_self: string[];
          lessons_life: string[];
          quotes_from_past_self: Json;
          warnings_to_future_self: string[];
          raw_notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          executive_summary?: string;
          strengths?: string[];
          growth_edges?: string[];
          energized_by?: string[];
          drained_by?: string[];
          optimal_conditions?: string;
          over_indexes?: string;
          under_weights?: string;
          blind_spots?: string[];
          goal_archaeology?: Json;
          insights_by_year?: Json;
          lessons_work?: string[];
          lessons_relationships?: string[];
          lessons_self?: string[];
          lessons_life?: string[];
          quotes_from_past_self?: Json;
          warnings_to_future_self?: string[];
          raw_notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          executive_summary?: string;
          strengths?: string[];
          growth_edges?: string[];
          energized_by?: string[];
          drained_by?: string[];
          optimal_conditions?: string;
          over_indexes?: string;
          under_weights?: string;
          blind_spots?: string[];
          goal_archaeology?: Json;
          insights_by_year?: Json;
          lessons_work?: string[];
          lessons_relationships?: string[];
          lessons_self?: string[];
          lessons_life?: string[];
          quotes_from_past_self?: Json;
          warnings_to_future_self?: string[];
          raw_notes?: string;
          updated_at?: string;
        };
      };
      interview_responses: {
        Row: {
          id: string;
          user_id: string;
          interview_type: string;
          responses: Json;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          interview_type: string;
          responses?: Json;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          interview_type?: string;
          responses?: Json;
          completed_at?: string | null;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
